services:
  postgres_db_original:
    image: postgres:18-alpine
    container_name: smart-home-postgres-original
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8432:5432"
    volumes:
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init-device.sql
    networks:
      - smarthome-network-original
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smarthome"]
      interval: 10s
      timeout: 5s
      retries: 5

  temperature-api:
    build:
      context: ${SMARTHOME_ORIGINAL}
      dockerfile: Dockerfile
    container_name: temperature-api
    environment:
      - ASPNETCORE_HTTP_PORTS=8081
    networks:
      - smarthome-network-original


  smart-home:
    build:
      context: ${SMARTHOME_ORIGINAL}
      dockerfile: Dockerfile
    container_name: smarthome-original
    depends_on:
      postgres_db_original:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network-original



volumes:
  postgres_data:

networks:
  smarthome-network-original:
    driver: bridge