@startuml

title Диаграмма контейнеров микросервисного решения для системы Smart home

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml


Person(User, "User", "Smarthome user")
System(SmartHome, "Smart home", "Smart home system control")
System_Ext(Device, "Device", "Home device")

Container_Boundary(SmartHome, "Smart home system control") {
    Container(WebApp, "Web Application", ".net, vue", "Handles user interactions")
    Container(DeviceService, "Device service", ".net", "Interacts with devices")
    Container(ProgramService, "Program service", ".net", "Device`s state machine")
    Container(DeviceDatabase, "Device database", "PostgreSql", "Store device`s info, states, programs")
    Container(ProgramDatabase, "Program database", "PostgreSql", "Store state machine, current states, programs")
}

Rel(User, WebApp,  "Uses smarthome web application")
Rel(WebApp, DeviceService,  "Request device`s info")
Rel(WebApp, ProgramService,  "Request program to control devices")
Rel(DeviceService, DeviceDatabase,  "Read/Write device`s info")
Rel(ProgramService, ProgramDatabase,  "Read/Write program/state info")
Rel(ProgramService, DeviceService,  "Control`s device`s by program")
Rel(DeviceService, Device,  "Read metrics/ use device")


@enduml